### ISSUE TITLE
Error code return from xmatchview-*.py

### ISSUE THREAD

**Issue by brook-milligan** [bcgsc/xmatchview#12]
Both xmatchview-conifer.py and xmatchview-hive.py end follow main() with sys.exit(1).  (xmatchview.py does not.)  The OS interprets this as an error, whereas it is presumably a successful completion of the program.  The sys.exit(1) should be removed from the last line of both of these programs.

**Comment by warrenlr** [comment]
thanks for reporting! these have now been fixed in the master branch
